### ISSUE TITLE
What is the difference between autosource and custom built scanner in sonarQube?

### ISSUE THREAD

**Issue by abhilashrao** [Securityautomation/autoSource#1]

**Comment by Securityautomation** [comment]
In a custom built scanner, user have to give project key and other parameters for each and every scan. Whereas using autoSource, user just have to give the link to repo and everything is taken care by tool itself. autoSource is an automated version for SonarQube.

**Comment by Securityautomation** [comment]
In a custom built scanner, user have to give project key and other parameters for each and every scan. Whereas using autoSource, user just have to give the link to repo and everything is taken care by tool itself. autoSource is an automated version for SonarQube.
